ID-B-4.3-4.4
Mekudo/PetFamily pull request #8
Opened 2024-11-25 17:48 UTC by Mekudo

2024-11-26 07:38 UTC, KirillSachkov requested changes

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/ModelBreed/Breed.cs
> +    public static Result<Breed> Create(BreedId id, NameShare nameShare, DescriptionShare description, SpecieId specieId)
В данном случае у тебя всё VO, поэтому в этом методе валидации никакой нет, поэтому можно исползовать просто конструктор

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/ModelBreed/ValueObject/BreedId.cs
> +    public static BreedId Create(Guid id)
можно использовать просто конструктор

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/ModelBreed/ValueObject/BreedId.cs
> +public record BreedId
я бы рекомендовал использвоать библиоетку CsharpFunctionalExtensions для VO и Entity

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/Pet.cs
> +            petId,
если здесь все VO, то смысла в Create нет

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/Species/Specie.cs
> +    public static Result<Specie> Create(SpecieId specieId,NameShare name, IReadOnlyList<Breed> breeds)
метод не нужен

2024-11-26 07:38 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/Species/Specie.cs
> +    public static Result<Specie> Create(SpecieId specieId,NameShare name, IReadOnlyList<Breed> breeds)
все остальные аналогичные места тоже нужно поправить

2024-11-26 18:48 UTC, Mekudo commented on PetFamily.Backend/src/PetFamily.Domain/Models/ModelPet/Species/Specie.cs
> +    public static Result<Specie> Create(SpecieId specieId,NameShare name, IReadOnlyList<Breed> breeds)
Исправил (коммит "fix"),чтобы через конструктор создавалось, не понял про "я бы рекомендовал использовать библиотеку CsharpFunctionalExtensions для VO и Entity" для id тоже стоит сделать валидацию? или можно для id можно без этого обойтись?

2024-11-27 07:57 UTC, KirillSachkov approved these changes

2024-11-27 08:19 UTC, merged